## Home page
# GET http://localhost:3000/

## Obtener los repositorios
# GET http://localhost:3000/repositories

## Obtener un repositorio por ID
# GET http://localhost:3000/repositories/tetris

## Insertar un repositorio 
# POST http://localhost:3000/repositories/tetris
# Content-Type: application/json
# {
#    name: "Tetris Game",
#    description: "its just a Tetris",
#    technologies: ["React", "JS", "nodeJS"],
#    updated: new Date(Number(new Date().getTime())).toLocaleString(),
# }

## Actualizar un repositorio
# PATCH http://localhost:3000/repositories/tetris

## Obtener el perfil del usuario
# GET http://localhost:3000/profile

## Insertar usuario
# POST http://localhost:3000/profile
# Content-Type: application/json

# {
#   name: "Nicolas Fuentes",
#   username: "NicolasFue05",
#   password: "nico"
# }

## Actualizar usuario
# PATCH http://localhost:3000/profile

